version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/secretlab
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/secretlab
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: deployment/change_ownership.sh
      timeout: 300
      runas: ec2-user
    - location: deployment/install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: deployment/deploy.sh
      timeout: 300
      runas: ec2-user
    - location: deployment/folder_permissions.sh
      timeout: 300
      runas: ec2-user
